location = "swedencentral"
# resource_group_name = "rg-demo-dev-swdenc-001"
rg_name_prefix       = "rg-demo-dev"
rg_name_suffix       = "001"
address_space        = "10.0.0.0/24"
subnet_name          = "subnet-demo"
storage_account_name = "stodemodevswe001fke"